export const GETQUESTION = 'GETQUESTION'
export const ADDQUESTION = 'ADDQUESTION'
export const DELETEQUESTION = 'DELETEQUESTION'
export const COUNTQUESTION = 'COUNTQUESTION'

export const ADDCOMMENT = 'ADDCOMMENT'
export const GETCOMMENT = 'GETCOMMENT'
export const DELETECOMMENT = 'DELETECOMMENT'
export const GETQUANTITYOFCOMMENT = 'GETQUANTITYOFCOMMENT'

export const ISLOADING = 'ISLOADING'
