//Question action
export const GETQUESTION = 'GETQUESTION'
export const ADDQUESTION = 'ADDQUESTION'
export const DELETEQUESTION = 'DELETEQUESTION'
export const COUNTQUESTION = 'COUNTQUESTION'

//Comment action
export const ADDCOMMENT = 'ADDCOMMENT'
export const GETCOMMENT = 'GETCOMMENT'
export const DELETECOMMENT = 'DELETECOMMENT'
export const GETQUANTITYOFCOMMENT = 'GETQUANTITYOFCOMMENT'

//Theme
export const ISDARKMODE = 'ISDARKMODE'
export const ISWHITEMODE = 'ISWHITEMODE'

export const ISLOADING = 'ISLOADING'

// Credential
export const USERLOGIN = 'USERLOGIN'
export const USERREGISTER = 'USERREGISTER'
export const LOADCREDENTIAL = 'LOADCREDENTIAL'
export const LOGINFAIL = 'LOGINFAIL'
export const REGISTERFAIL = 'REGISTERFAIL'
